/**
 * app
 */
export const APP_GET_USER_INFO = 'APP/APP_GET_USER_INFO'
export const APP_GET_FUND_FIRM = 'APP/APP_GET_FUND_FIRM'
export const APP_MENU_STATE = 'APP/APP_MENU_STATE'
export const APP_MENU_BTN_COLOR = 'APP/APP_MENU_BTN_COLOR'
export const APP_ASSISTANT_MENU = 'APP/APP_ASSISTANT_MENU'
export const APP_LOGIN_BOX = 'APP/APP_LOGIN_BOX'
export const APP_INNER_SIZE = 'APP/APP_INNER_SIZE'
export const APP_INDEX_MENU_STATE = 'APP/APP_INDEX_MENU_STATE'
/**
 * permission
 */
export const PERM_ROUTER_PERMISSION = 'PERMISSION/PERM_ROUTER_PERMISSION'

/**
 * place
 */
export const ACTIVE_PLACE = 'PLACE/ACTIVE_PLACE'
export const PLACE_LIST = 'PLACE/PLACE_LIST'
export const MINORITY_LIST = 'PLACE/MINORITY_LIST'
export const MINORITY_LIST_ALL = 'PLACE/MINORITY_LIST_ALL'
export const MINORITY_CONTENT = 'PLACE/MINORITY_CONTENT'
